// <auto-generated />
namespace Train.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201610200646224_removeCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
